version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypass
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventoryuser -d inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: inventory-backend
    environment:
      DATABASE_URL: postgresql://inventoryuser:inventorypass@postgres:5432/inventory
      FLASK_ENV: development
      FLASK_APP: app
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: python run.py

  nginx:
    image: nginx:alpine
    container_name: inventory-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
