"""Remove quantity and unit fields from items

Revision ID: 40319a559919
Revises: 
Create Date: 2025-10-27 14:38:45.599500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40319a559919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
