"""Add Bin model, BinLocation, and Item embedding for semantic search

Revision ID: 6bcf6f19115a
Revises: 
Create Date: 2025-11-01 20:06:14.178470

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '6bcf6f19115a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_locations', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
        batch_op.add_column(sa.Column('bin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bins', ['bin_id'], ['id'])
        batch_op.drop_column('unit')
        batch_op.drop_column('min_quantity')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bin_id')
        batch_op.drop_column('embedding')

    with op.batch_alter_table('item_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
